[env:4d_systems_esp32s3_gen4_r8n16]

platform = espressif32@6.8.1
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino

upload_speed = 115200

monitor_port = COM16
monitor_speed = 115200


lib_deps =
    lvgl/lvgl@8.4.0
    bodmer/TFT_eSPI@2.5.43